//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.233
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hy.Check.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hy.Check.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BGJCJG {
            get {
                object obj = ResourceManager.GetObject("BGJCJG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CloseTask {
            get {
                object obj = ResourceManager.GetObject("CloseTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Contact {
            get {
                object obj = ResourceManager.GetObject("Contact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DataSample {
            get {
                object obj = ResourceManager.GetObject("DataSample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExcuteTask {
            get {
                object obj = ResourceManager.GetObject("ExcuteTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportFolderButton {
            get {
                object obj = ResourceManager.GetObject("ExportFolderButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportToExcel {
            get {
                object obj = ResourceManager.GetObject("ExportToExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportToExcel1 {
            get {
                object obj = ResourceManager.GetObject("ExportToExcel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportToExcel2 {
            get {
                object obj = ResourceManager.GetObject("ExportToExcel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportToShp {
            get {
                object obj = ResourceManager.GetObject("ExportToShp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExportToVCT {
            get {
                object obj = ResourceManager.GetObject("ExportToVCT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileStruct {
            get {
                object obj = ResourceManager.GetObject("FileStruct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HZBG {
            get {
                object obj = ResourceManager.GetObject("HZBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Identify {
            get {
                object obj = ResourceManager.GetObject("Identify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Import2MDB {
            get {
                object obj = ResourceManager.GetObject("Import2MDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LabelError {
            get {
                object obj = ResourceManager.GetObject("LabelError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ManualSample {
            get {
                object obj = ResourceManager.GetObject("ManualSample", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Message_Email {
            get {
                object obj = ResourceManager.GetObject("Message_Email", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewTask {
            get {
                object obj = ResourceManager.GetObject("NewTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewTask1 {
            get {
                object obj = ResourceManager.GetObject("NewTask1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewTask2 {
            get {
                object obj = ResourceManager.GetObject("NewTask2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Note {
            get {
                object obj = ResourceManager.GetObject("Note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PropertyView {
            get {
                object obj = ResourceManager.GetObject("PropertyView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonPrintPreview_Customize {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Customize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonPrintPreview_CustomizeLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonPrintPreview_HandTool {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_HandTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonPrintPreview_Pointer {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_Pointer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintSetup {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonPrintPreview_PrintSetupLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignBottom {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignHorizontalCenters {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignHorizontalCenters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignLeft {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignRight {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignToGrid {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignToGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignTop {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_AlignVerticalCenters {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_AlignVerticalCenters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_BackColor {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_BackColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_BringToFront {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_BringToFront", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_CenterHorizontally {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_CenterHorizontally", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_CenterVertically {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_CenterVertically", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Copy {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_CopyLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_CopyLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Cut {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_CutLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_CutLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Edit {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Font {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_FontBold {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_FontBold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_FontItalic {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_FontItalic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_FontUnderline {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_FontUnderline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_ForeColor {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_ForeColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HorizSpaceConcatenate {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceConcatenate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HorizSpaceDecrease {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceDecrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HorizSpaceIncrease {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceIncrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HorizSpaceMakeEqual {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HorizSpaceMakeEqual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlBackward {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlBackward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlBackwardLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlBackwardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlFind {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlFindLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlFindLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlForward {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlForwardLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlForwardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlHome {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlHome", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlHomeLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlHomeLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlRefresh {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlRefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlRefreshLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlRefreshLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlStop {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_HtmlStopLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_HtmlStopLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_JustifyCenter {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_JustifyCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_JustifyJustify {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_JustifyJustify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_JustifyLeft {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_JustifyLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_JustifyRight {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_JustifyRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_NewReport {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_NewReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_NewReportLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_NewReportLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_NewReportWizard {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_NewReportWizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_NewReportWizardLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_NewReportWizardLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_OpenFile {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_OpenFileLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_OpenFileLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Paste {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_PasteLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_PasteLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Redo {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_RedoLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_RedoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Report {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SaveFile {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SaveFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SaveFileAs {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SaveFileAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SaveFileAsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SaveFileAsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SaveFileLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SaveFileLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SendToBack {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SendToBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SizeToControl {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SizeToControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SizeToControlHeight {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SizeToControlHeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SizeToControlWidth {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SizeToControlWidth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_SizeToGrid {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_SizeToGrid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Undo {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_UndoLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_UndoLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_VertSpaceConcatenate {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceConcatenate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_VertSpaceDecrease {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceDecrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_VertSpaceIncrease {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceIncrease", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_VertSpaceMakeEqual {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_VertSpaceMakeEqual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Windows {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Windows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_WindowsLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_WindowsLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_Zoom {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_Zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_ZoomIn {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_ZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_ZoomInLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_ZoomInLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_ZoomLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_ZoomLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_ZoomOut {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_ZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RibbonUserDesigner_ZoomOutLarge {
            get {
                object obj = ResourceManager.GetObject("RibbonUserDesigner_ZoomOutLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShpToMDB {
            get {
                object obj = ResourceManager.GetObject("ShpToMDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SJJCJGB {
            get {
                object obj = ResourceManager.GetObject("SJJCJGB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StartManualCheck {
            get {
                object obj = ResourceManager.GetObject("StartManualCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopManualCheck {
            get {
                object obj = ResourceManager.GetObject("StopManualCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TaskHistory {
            get {
                object obj = ResourceManager.GetObject("TaskHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TaskProperty {
            get {
                object obj = ResourceManager.GetObject("TaskProperty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TaskRule {
            get {
                object obj = ResourceManager.GetObject("TaskRule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TopoView {
            get {
                object obj = ResourceManager.GetObject("TopoView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VCT2MDB {
            get {
                object obj = ResourceManager.GetObject("VCT2MDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap VCTtoMDB {
            get {
                object obj = ResourceManager.GetObject("VCTtoMDB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap XZQIdentify {
            get {
                object obj = ResourceManager.GetObject("XZQIdentify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ZLWZXJLB {
            get {
                object obj = ResourceManager.GetObject("ZLWZXJLB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 全幅显示 {
            get {
                object obj = ResourceManager.GetObject("全幅显示", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 删除图形 {
            get {
                object obj = ResourceManager.GetObject("删除图形", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 点选 {
            get {
                object obj = ResourceManager.GetObject("点选", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap 移动 {
            get {
                object obj = ResourceManager.GetObject("移动", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
