///////////////////////////////////////////////////////////
//  MDB2VCTForm.cs
//  Implementation of the Class MDB2VCTForm
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:31
//  Original author: Administrator
///////////////////////////////////////////////////////////



using DIST.DGP.DataExchange.VCT;
namespace DIST.DGP.DataExchange.VCTUI {
	/// <summary>
	/// PGDB数据转为VCT窗口类
	/// </summary>
	public class MDB2VCTForm:System.Windows.Forms.Form
    {

		public MDB2VCT m_MDB2VCT;

		public MDB2VCTForm()
        {

		}

		~MDB2VCTForm(){

		}

		public virtual void Dispose(){

		}

        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // MDB2VCTForm
            // 
            this.ClientSize = new System.Drawing.Size(450, 338);
            this.Name = "MDB2VCTForm";
            this.Text = "MDB转VCT";
            this.ResumeLayout(false);

        }

	}//end MDB2VCTForm

}//end namespace VCTUI