///////////////////////////////////////////////////////////
//  EsriDataSource.cs
//  Implementation of the Class EsriDataSource
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:30
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.ESRIData;
using DIST.DGP.DataExchange.VCT.FileData;
using ESRI.ArcGIS.Geodatabase;
using System;
using ESRI.ArcGIS.Geometry;
namespace DIST.DGP.DataExchange.VCT {
	/// <summary>
	/// 数据源类
	/// </summary>
	internal class EsriDataSource {

		/// <summary>
		/// 数据源连接
		/// </summary>
		private IWorkspace m_pIWorkspace;
        public IWorkspace Workspace
        {
            get
            {
                return m_pIWorkspace;
            }
            set
            {
                m_pIWorkspace = value;
            }
        }
		public Dataset m_Dataset;

        protected ArcDataType m_dataType= ArcDataType.MDB;
        /// <summary>
        /// 数据转换中arcgis的数据类型（mdb，fgdb）
        /// </summary>
        public ArcDataType DataType
        {
            get
            {
                return m_dataType;
            }
        }

        protected IGeometry m_CutGeometry=null;
        /// <summary>
        /// 裁切范围
        /// </summary>
        public IGeometry CutGeometry
        {
            get
            {
                return m_CutGeometry;
            }
        }

        protected bool m_bCut=false;
        /// <summary>
        /// 是否裁剪
        /// </summary>
        public bool IsCut
        {
            get
            {
                return m_bCut;
            }
        }
		public EsriDataSource(){

		}

		~EsriDataSource(){

		}

		public virtual void Dispose()
        {
            if (m_Dataset != null)
                m_Dataset.Dispose();
            if (this.Workspace != null)
                System.Runtime.InteropServices.Marshal.ReleaseComObject(Workspace);
            m_Dataset = null;
            Workspace = null;
            GC.Collect();
		}

		/// <summary>
		/// 创建数据集
		/// </summary>
		/// <param name="headNode">VCT头节点</param>
        public Dataset CreateDataset(HeadNode headNode, string strName)
        {
            if (headNode == null)
                return null;
            try
            {
                m_Dataset = new Dataset(m_pIWorkspace);
                if (m_Dataset.CreateESRIDataset(strName, headNode))
                    return m_Dataset;

                return m_Dataset;
            }
            catch (Exception ex)
            {
                Logger.WriteErrorLog(ex);
                return null;
            }
        }

		/// <summary>
		/// 打开数据集
		/// </summary>
        public Dataset GetDataset()
        {
            IEnumDataset pEnumDataset = m_pIWorkspace.get_Datasets(esriDatasetType.esriDTFeatureDataset);
            IDataset pIDataset = pEnumDataset.Next();
            if (pIDataset != null)
            {
                m_Dataset = new Dataset(pIDataset,m_pIWorkspace,m_bCut,m_CutGeometry);

                return m_Dataset;
            }
            return null;
        }

	}//end EsriDataSource

    /// <summary>
    /// arcgis数据类型
    /// </summary>
    public enum ArcDataType
    {
        /// <summary>
        /// mdb数据
        /// </summary>
        MDB,

        /// <summary>
        /// fgdb数据
        /// </summary>
        FGDB
    }

    public enum EnumMDB2VCTExchangeInfo
    {
        /// <summary>
        /// 转换成功
        /// </summary>
        EXCHANGESUCCESS = 0,


        /// <summary>
        /// 生成头文件错误
        /// </summary>
        HEADFILEERROR = 1,

        /// <summary>
        /// 读取数据集信息错误
        /// </summary>
        DATASETERROR = 2,

        /// <summary>
        /// 生成要素代码和表结构错误
        /// </summary>
        FEATUREINFOERROR = 3,

        ///// <summary>
        ///// 生成表结构错误
        ///// </summary>
        //FEATURESTRUCT = 4,

        /// <summary>
        /// 生成点实体错误
        /// </summary>
        POINTERROR = 5,

        /// <summary>
        /// 生成线实体错误
        /// </summary>
        LINEERROR = 6,

        /// <summary>
        /// 生成面实体错误
        /// </summary>
        PLOYGONERROR=7,

        /// <summary>
        /// 读取数据投影信息错误
        /// </summary>
        PROJCTIONERROR = 8,

        /// <summary>
        /// 转换未知异常
        /// </summary>
        EXCHANGUNKNOWEERROR = 9,

        /// <summary>
        /// 转换失败
        /// </summary>
        EXCHANGFAIL = 9,

    }

}//end namespace VCT