#ifndef _DD_PACKAGE_VERSION_INCLUDED_
#define _DD_PACKAGE_VERSION_INCLUDED_

/** OLD HEADER. USE CONSTANTS FROM "DDVersion.h" INSTEAD **/

#include "DDVersion.h"

#define DD_VER_MAJOR  DD_MAJOR_VERSION
#define DD_VER_MINOR  DD_MINOR_VERSION

#endif //#ifndef _DD_PACKAGE_VERSION_INCLUDED_

