///////////////////////////////////////////////////////////
//  BellCurveNode.cs
//  Implementation of the Class BellCurveNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:30
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT贝尔赛曲线节点类
	/// </summary>
	public class BellCurveNode : SegmentNode {

		public BellCurveNode():base(17){

		}

        //~BellCurveNode(){

        //}

        //public override void Dispose(){

        //}

	}//end BellCurveNode

}//end namespace FileData