///////////////////////////////////////////////////////////
//  CenterArcNode.cs
//  Implementation of the Class CenterArcNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:30
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT圆心弧节点类
	/// </summary>
	public class CenterArcNode : SegmentNode {

		private PointInfoNode centerPointNode;
		private double dEndAngle;
		private double dRadius;
		private double dStartAngle;
		public PointInfoNode m_PointInfoNode;
		/// <summary>
		/// 中心点
		/// </summary>
		private PointInfoNode m_centerPointInfoNode;
		/// <summary>
		/// 终止角
		/// </summary>
		private double m_dEndAngle;
		/// <summary>
		/// 半径
		/// </summary>
		private double m_dRadius;
		/// <summary>
		/// 起始角
		/// </summary>
		private double m_dStartAngle;

        public CenterArcNode()
            : base(13)
        {

		}

        //~CenterArcNode(){

        //}

        //public override void Dispose(){

        //}

	}//end CenterArcNode

}//end namespace FileData