///////////////////////////////////////////////////////////
//  ConstantNode.cs
//  Implementation of the Class ConstantNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:30
//  Original author: Administrator
///////////////////////////////////////////////////////////




namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT常量节点类
	/// </summary>
	public class ConstantNode {

		public ConstantNode(){

		}

		~ConstantNode(){

		}

		public virtual void Dispose(){

		}

	}//end ConstantNode

}//end namespace FileData