///////////////////////////////////////////////////////////
//  RepresentationNode.cs
//  Implementation of the Class RepresentationNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT图形表现编码节点类
	/// </summary>
	public class RepresentationNode {

		public RepresentationNode(){

		}

		~RepresentationNode(){

		}

		public virtual void Dispose(){

		}

	}//end RepresentationNode

}//end namespace FileData