///////////////////////////////////////////////////////////
//  SplineNode.cs
//  Implementation of the Class SplineNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT样条曲线节点类
	/// </summary>
	public class SplineNode : SegmentNode {

		public SplineNode():base(16){

		}

        //~SplineNode(){

        //}

        //public override void Dispose(){

        //}

	}//end SplineNode

}//end namespace FileData