///////////////////////////////////////////////////////////
//  StyleNode.cs
//  Implementation of the Class StyleNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT图形表现节点类
	/// </summary>
	public class StyleNode {

		public ConstantNode m_ConstantNode;
		public RelationTableNode m_RelationTableNode;
		public RepresentationNode m_RepresentationNode;

		public StyleNode(){

		}

		~StyleNode(){

		}

		public virtual void Dispose(){

		}

	}//end StyleNode

}//end namespace FileData