///////////////////////////////////////////////////////////
//  ThreeSplineNode.cs
//  Implementation of the Class ThreeSplineNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT三次样条曲线节点类
	/// </summary>
	public class ThreeSplineNode : SegmentNode {

        public ThreeSplineNode()
            : base(15)
        {

		}

        //~ThreeSplineNode(){

        //}

        //public override void Dispose(){

        //}

	}//end ThreeSplineNode

}//end namespace FileData