///////////////////////////////////////////////////////////
//  VarcharNode.cs
//  Implementation of the Class VarcharNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT变长字符串节点类
	/// </summary>
	public class VarcharNode {

		public VarcharNode(){

		}

		~VarcharNode(){

		}

		public virtual void Dispose(){

		}

	}//end VarcharNode

}//end namespace FileData