///////////////////////////////////////////////////////////
//  PolygonLayer.cs
//  Implementation of the Class PolygonLayer
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:32
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.ESRIData;
using DIST.DGP.DataExchange.VCT.FileData;
using System.Collections.Generic;
using ESRI.ArcGIS.Geodatabase;
using System;
namespace DIST.DGP.DataExchange.VCT.ESRIData {
	/// <summary>
	/// 多边形图层类
	/// </summary>
	public class PolygonLayer : FeatureLayer {

		public PolygonEntity m_PolygonEntity;

		public PolygonLayer(){

		}

		~PolygonLayer(){

		}

		public override void Dispose()
        {
            base.Dispose();
		}

        /// <summary>
        /// 创建
        /// </summary>
        public override bool Create(TableStructureNode tableStructureNode)
        {
            base.Create(tableStructureNode);

            return true;
        }

		/// <summary>
		/// 创建面实体
		/// </summary>
		/// <param name="entinyNode">VCT面实体节点</param>
		public override FeatureEntity CreateFeatureEntity(EntityNode entinyNode)
        {
            if (entinyNode is PolygonNode)
            {
                m_PolygonEntity = new PolygonEntity();
                m_PolygonEntity.SetFeatureKeyFieldName(m_strEntityFieldName, m_strSYDMFieldName);
                m_PolygonEntity.CreateFeature(this.Table, entinyNode);
                return m_PolygonEntity;
            }
            return null;
		}

        /// <summary>
        /// 获取实体集合
        /// </summary>
        public override List<FeatureEntity> GetFeatureEntitys()
        {
            try
            {
                IFeatureClass pFeatureCls = this.Table as IFeatureClass;
                IFeatureCursor pCursor = pFeatureCls.Search(null, false);
                IFeature pFeature = pCursor.NextFeature();
                List<FeatureEntity> listFeatureEnty = new List<FeatureEntity>();//保存FeatureEntity
                while (pFeature != null)
                {
                    ///add by 曾平2011-9-7 添加裁切判断
                    ///裁切范围为空表示不进行裁切
                    if (m_CutGeometry != null)
                    {
                        if (!FeatureInCutRegion(pFeature.Shape))
                        {
                            pFeature = pCursor.NextFeature();
                            continue;
                        }
                    }

                    PolygonEntity pPointEntity = new PolygonEntity();
                    pPointEntity.CutGeometry = m_CutGeometry;
                    pPointEntity.IsCut = m_bCut;
                    pPointEntity.Feature = pFeature;
                    ///初始化相关数据
                    //pPointEntity.GetEntityNode();
                    pPointEntity.FeatureCode = this.FeatureCode;
                    int nEntityIDIndex = -1;
                    nEntityIDIndex = pFeature.Fields.FindField(m_strEntityFieldName);
                    if(nEntityIDIndex!=-1)
                        pPointEntity.EntityID =Convert.ToInt32( pFeature.get_Value(nEntityIDIndex));


                    ///设置要素代码和标识码
                    pPointEntity.SetFeatureKeyFieldName(m_strEntityFieldName, m_strSYDMFieldName);


                    listFeatureEnty.Add(pPointEntity);
                    pFeature = pCursor.NextFeature();
                }
                m_FeatureEntys = listFeatureEnty;
                return listFeatureEnty;
            }
            catch (Exception ex)
            {
                LogAPI.WriteErrorLog(ex);
                return null;
            }
        }

	}//end PolygonLayer

}//end namespace ESRIData