///////////////////////////////////////////////////////////
//  AttributeNode.cs
//  Implementation of the Class AttributeNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:30
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT实体属性节点类
	/// </summary>
	public class AttributeNode {

		public TableNode m_TableNode;
		public VarcharNode m_VarcharNode;

		public AttributeNode(){

		}

		~AttributeNode(){

		}

		public virtual void Dispose(){

		}

	}//end AttributeNode

}//end namespace FileData