///////////////////////////////////////////////////////////
//  OvalArcNode.cs
//  Implementation of the Class OvalArcNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:32
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT椭圆弧节点类
	/// </summary>
	public class OvalArcNode : SegmentNode {

		private PointNode centerPointNode;
		private double dEndAngle;
		private double dRatio;
		private double dStartAngle;
		private double relativePointNode;
		public PointInfoNode m_PointInfoNode;
		/// <summary>
		/// 椭圆中心点坐标
		/// </summary>
		private PointInfoNode m_CenterPointInfoNode;
		/// <summary>
		/// 终止角
		/// </summary>
		private double m_dEndAngle;
		/// <summary>
		/// 短半轴与长半轴的比率
		/// </summary>
		private double m_dRatio;
		/// <summary>
		/// 起始角
		/// </summary>
		private double m_dStartAngle;
		/// <summary>
		/// 长半轴端点相对于中心点坐标
		/// </summary>
		private double m_relativePointNode;

        public OvalArcNode()
            : base(14)
        {

		}

        //~OvalArcNode(){

        //}

        //public override void Dispose(){

        //}

	}//end OvalArcNode

}//end namespace FileData