///////////////////////////////////////////////////////////
//  PointNode.cs
//  Implementation of the Class PointNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:32
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
using System.Collections.Generic;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT点实体节点类
	/// </summary>
	public class PointNode : EntityNode {


		/// <summary>
		/// 点数
		/// </summary>
        private int m_nPointCount = 1;
        public int PointCount
        {
            get
            {
                return m_nPointCount;
            }
            set
            {
                m_nPointCount = value;
            }
        }

		/// <summary>
        /// 点的特征类型。其中：1表示独立点，2表示结点。独立点、结点的点数为1。
		/// </summary>
        public int PointType
        {
            get
            {
                return m_nPointType;
            }
            set
            {
                m_nPointType = value;
            }
        }
        private int m_nPointType;

        /// <summary>
        /// 点的坐标
        /// </summary>
        public PointInfoNode PointInfoNode
        {
            get
            {
                return m_PointInfoNode;
            }
            set
            {
                m_PointInfoNode = value;
            }
        }
        private PointInfoNode m_PointInfoNode;
        
        public PointNode(){

		}      

        //~PointNode()
        //{

        //}

        //public override void Dispose(){

        //}
        /// <summary>
        /// 输出VCT节点
        /// </summary>
        public override string ToString()
        {
            string strNode = base.ToString();
            strNode += "\r\n" + this.m_nPointType.ToString();
            strNode += "\r\n" + this.m_nPointCount.ToString();
            strNode += "\r\n" + this.m_PointInfoNode.ToString();
            strNode += "\r\n0";

            return strNode;
        }
	}//end PointNode

}//end namespace FileData