///////////////////////////////////////////////////////////
//  RelationTableNode.cs
//  Implementation of the Class RelationTableNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT值对应表节点类
	/// </summary>
	public class RelationTableNode {

		public RelationTableNode(){

		}

		~RelationTableNode(){

		}

		public virtual void Dispose(){

		}

	}//end RelationTableNode

}//end namespace FileData