///////////////////////////////////////////////////////////
//  TableNode.cs
//  Implementation of the Class TableNode
//  Generated by Enterprise Architect
//  Created on:      08-四月-2011 13:45:33
//  Original author: Administrator
///////////////////////////////////////////////////////////




using DIST.DGP.DataExchange.VCT.FileData;
namespace DIST.DGP.DataExchange.VCT.FileData {
	/// <summary>
	/// VCT属性数据表节点类
	/// </summary>
	public class TableNode {

		/// <summary>
		/// 属性表名
		/// </summary>
        public string TableName
        {
            get
            {
                return m_strTableName;
            }
            set
            {
                m_strTableName = value;
            }
        }
		private string m_strTableName;

		public TableNode(){

		}

		~TableNode(){

		}

		public virtual void Dispose(){

		}

        /// <summary>
        /// 输出VCT节点
        /// </summary>
        public override string ToString()
        {
            return m_strTableName;
        }

	}//end TableNode

}//end namespace FileData